* EQ-lips schematic
** Description
Electronic schematics of EQ-lips.

EQ-lips is a graphic equalizer pedal effect with the following
features:
  - 10 bands of EQ and global gain control with a range of +/-18dB
  - 23 memory banks
  - Analog signal treatment
  - Equalization configuration with LCD and rotary encoder

Schematics have been realized with [[http://www.lis.inpg.fr/realise_au_lis/kicad/][Kicad]]. They use specific components and
footprints which can be found in submodule /kicad_lib/. This submodule
is also available at the following address: [[http://github.com/cbr/kicad_lib]].

The firmware of EQ-lips can be found here:
[[http://github.com/cbr/EQ-lips-firmware]]. The followings tools have also
been used during the design of these schematics:
[[http://github.com/cbr/EQ-lips-tools]].

The bill of materials (BOM) can be found in [[http://github.com/cbr/EQ-lips-schematic/blob/master/bom.ods][bom.ods]] (OpenDocument
Spreadsheet file format which can be opened with OpenOffice.org).

** Version
*** 1.0.0
This first a prototype has been manufactured. Some mistakes have been
corrected to give version 1.1.0.
*** 1.1.0
This version has not been manufactured (NOT TESTED). It fixes mistakes
encountered on 1.0.0 version and brings some PCB enhancements.

** Author
Cédric Brégardis (cedric.bregardis <at> gmail.com)
** Licence
This work is licensed under the Creative Commons
Attribution-NonCommercial-ShareAlike 3.0 Unported License. To view a copy of
this license, visit [[http://creativecommons.org/licenses/by-nc-sa/3.0/]] or send
a letter to Creative Commons, 171 Second Street, Suite 300, San Francisco,
California, 94105, USA.
